#!/usr/pkg/bin/bash
#Test all driver functionality
# Input is the slot to manipulate (set & clear) (defaults to 0)

if [ "$1" = "" ]; then
    slot="0";
else
    slot="$1";
fi
echo -e "\e[4mHOMEWORK2 DEVICE DRIVER TEST\e[0m";

echo "Turning off the device driver";
/root/os/os_p2/driver_test/down;

echo "Turning on the device driver";
/root/os/os_p2/driver_test/up;

echo "Reading the device driver (default slot)";
/root/os/os_p2/driver_test/read;

echo "Writing 50 to the device driver";
/root/os/os_p2/driver_test/write 50;

echo "Reading the device driver (default slot)";
/root/os/os_p2/driver_test/read;

echo "Doing IOCTL:";
echo "  Changing the active slot to $slot";
echo "  Getting the current slot (should be $slot)";
echo "  Clearing slot $slot";
/root/os/os_p2/driver_test/ioctl $slot;

echo "Confirm new slot is empty and works with a read(), write(), read():"
/root/os/os_p2/driver_test/read;
/root/os/os_p2/driver_test/write;
/root/os/os_p2/driver_test/read;

echo "Now it's your turn...(the driver is still up/running)"
